export const courses = [
  {
    slug: "sql",
    name: "SQLingo",
    tagline: "SQL, from first principles",
    description:
      "A 29-chapter, hands-on SQL handbook with a real database running in your browser. Write real queries, get real results, no setup required.",
    chapters: 29,
    status: "available",
    href: "/courses/sql",
    practiceMode: "live-code",
    questions: 115,
    progressKey: "sqlingo_progress",
  },
  {
    slug: "business-analyst",
    name: "BA Track",
    tagline: "Become a Business Analyst",
    description:
      "Requirements gathering, BRDs and user stories, process mapping, stakeholder management, and Agile delivery, taught the same hands-on way as SQLingo.",
    chapters: 32,
    status: "available",
    href: "/courses/business-analyst",
    practiceMode: "guided",
    questions: 91,
    progressKey: "ba_progress",
  },
  {
    slug: "qa",
    name: "QA Track",
    tagline: "Software testing, done right",
    description: "Manual and automated testing, test case design, bug reports that get fixed fast, and the tools QA teams use every day.",
    chapters: 32,
    status: "available",
    href: "/courses/qa",
    practiceMode: "guided",
    questions: 60,
    progressKey: "qa_progress",
  },
  {
    slug: "dev-fundamentals",
    name: "Dev: Fundamentals",
    tagline: "How software actually works",
    description:
      "What software and the SDLC are, how the internet and Git actually work, and the servers, reverse proxies, containers, and serverless concepts that confuse even experienced developers.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-fundamentals",
    practiceMode: "guided",
    questions: 39,
    progressKey: "devfund_progress",
  },
  {
    slug: "dev-python",
    name: "Dev: Python",
    tagline: "The language everything else is built on",
    description: "Real, live Python running in your browser: syntax, data structures, functions, and object-oriented code, building toward Django and FastAPI.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-python",
    practiceMode: "live-code",
    questions: 34,
    progressKey: "python_progress",
  },
  {
    slug: "dev-django",
    name: "Dev: Django",
    tagline: "Build a full web application",
    description: "Models, views, templates, the admin panel, auth, and shipping a complete Django web app, using the TastyGo case study.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-django",
    practiceMode: "guided",
    questions: 33,
    progressKey: "django_progress",
  },
  {
    slug: "dev-fastapi",
    name: "Dev: FastAPI",
    tagline: "Build a fast, modern API",
    description: "Routing, validation, async, dependency injection, and auto-generated docs, building TastyGo's API with FastAPI.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-fastapi",
    practiceMode: "guided",
    questions: 32,
    progressKey: "fastapi_progress",
  },
  {
    slug: "dev-devops",
    name: "Dev: DevOps",
    tagline: "Ship it, and keep it running",
    description: "Docker, reverse proxies, CI/CD pipelines, cloud deployment, and monitoring, the skills that get real software in front of real users.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-devops",
    practiceMode: "guided",
    questions: 33,
    progressKey: "devops_progress",
  },
  {
    slug: "dev-capstone",
    name: "Dev: Capstone Project",
    tagline: "Build TastyGo's backend from scratch",
    description: "Bring Python, a web framework, and DevOps together: build, containerize, and deploy a real, working slice of TastyGo's backend.",
    chapters: 32,
    status: "available",
    href: "/courses/dev-capstone",
    practiceMode: "mixed",
    questions: 32,
    progressKey: "capstone_progress",
  },
];
