// Plain-English glossary of software terms. Analogy-first, for career-switchers.
// Each term becomes its own server-rendered, indexable page at /explained/<slug>.

export const categories = ["Web basics", "Backend & servers", "Security & auth", "Infrastructure", "Data", "Under the hood", "Dev workflow"];

export const terms = [
  {
    slug: "frontend",
    term: "Frontend",
    category: "Web basics",
    oneLiner: "The part of an app you actually see and click, running in your browser.",
    analogy: "The dining area of a restaurant — the tables, menu, and decor the customer sees and touches.",
    detail: [
      "The frontend is everything that happens in the browser: the layout, buttons, text, and animations, built with HTML, CSS, and JavaScript.",
      "It sends requests to the backend when it needs data (like your orders) and shows the results. It handles how things look and feel, not where the data lives.",
    ],
    related: ["backend", "client", "server", "api"],
    course: { label: "Dev: Fundamentals", href: "/courses/dev-fundamentals" },
  },
  {
    slug: "backend",
    term: "Backend",
    category: "Backend & servers",
    oneLiner: "The behind-the-scenes part that does the work and stores the data.",
    analogy: "The kitchen of a restaurant — out of sight, it prepares what the dining area serves.",
    detail: [
      "The backend runs on a server. It does the actual work — checking your login, saving an order, fetching your data — talks to the database, and sends the results back to the frontend.",
      "Users never see it directly; they only see the results it sends back through an API.",
    ],
    related: ["frontend", "server", "database", "api"],
    course: { label: "Dev: Fundamentals", href: "/courses/dev-fundamentals" },
  },
  {
    slug: "client",
    term: "Client",
    category: "Web basics",
    oneLiner: "Whatever makes a request — usually your browser or app.",
    analogy: "The diner who places an order and waits for it to arrive.",
    detail: [
      "In the client-server model, the client asks and the server answers. Your browser is a client; so is a mobile app or another program calling an API.",
    ],
    related: ["server", "frontend", "api"],
  },
  {
    slug: "server",
    term: "Server",
    category: "Backend & servers",
    oneLiner: "A computer that waits for requests and sends back responses.",
    analogy: "A shop clerk: you ask for something, they fetch it and hand it over.",
    detail: [
      "A server is just a computer running a program that listens for requests (like web page or data requests) and replies. The same machine can run several servers on different ports.",
      "'Server' can mean the physical machine or the software doing the serving.",
    ],
    related: ["client", "backend", "port", "reverse-proxy"],
  },
  {
    slug: "api",
    term: "API",
    category: "Web basics",
    oneLiner: "A way for two pieces of software to talk to each other.",
    analogy: "A waiter at a restaurant. You don't march into the kitchen and cook — you tell the waiter what you want, and they bring it back. An API is that waiter sitting between two programs.",
    detail: [
      "API stands for Application Programming Interface, but the idea is simple: it's the agreed way to ask one program for something and get an answer back.",
      "For example, a weather app on your phone doesn't know the weather itself. It asks a weather company's API \"what's the forecast for Mumbai?\" and gets the answer — without needing to know anything about how that company's computers work inside.",
      "Almost every app you use is quietly making dozens of these requests in the background.",
    ],
    related: ["rest", "json", "backend", "frontend"],
    course: { label: "Dev: FastAPI", href: "/courses/dev-fastapi" },
  },
  {
    slug: "rest",
    term: "REST API",
    category: "Web basics",
    oneLiner: "The most common set of conventions for how web APIs are laid out.",
    analogy: "A standard ordering etiquette every waiter follows, so you always know how to ask.",
    detail: [
      "REST is just an agreed way to organise an API so it feels predictable. Each thing (an order, a user) gets its own web address, and you act on it with a few standard actions: get it, create it, update it, or delete it.",
      "Those are the same simple actions the web already uses behind the scenes, so once you've used one REST API, the next one feels familiar.",
    ],
    related: ["api", "http-https", "json"],
    course: { label: "Dev: FastAPI", href: "/courses/dev-fastapi" },
  },
  {
    slug: "http-https",
    term: "HTTP & HTTPS",
    category: "Web basics",
    oneLiner: "The language browsers and servers use to talk — HTTPS is the private, sealed version.",
    analogy: "HTTP is a postcard anyone handling it can read; HTTPS is a sealed, tamper-proof envelope.",
    detail: [
      "HTTP is the set of rules browsers and servers follow to ask for and send web pages. HTTPS is the same thing but scrambled (encrypted), so nobody in between can read or secretly change it, and you can trust you're really talking to the site you meant.",
      "Every real site should use HTTPS; browsers now warn on plain HTTP.",
    ],
    related: ["dns", "rest", "reverse-proxy"],
  },
  {
    slug: "dns",
    term: "DNS",
    category: "Web basics",
    oneLiner: "The internet's phone book — it turns a name into an address.",
    analogy: "Your contacts app: you tap 'Mom', it dials the actual number for you.",
    detail: [
      "DNS (Domain Name System) translates a human name like careerladder.io into the numeric IP address a computer needs to connect. It happens automatically before your browser can load a site.",
    ],
    related: ["http-https", "server", "cdn"],
  },
  {
    slug: "json",
    term: "JSON",
    category: "Web basics",
    oneLiner: "A simple, human-readable way to write data as labelled boxes and lists.",
    analogy: "A neatly labelled form: name here, age there, a list of hobbies below.",
    detail: [
      "JSON (JavaScript Object Notation) writes data as labelled values and lists, e.g. {\"name\": \"Priya\", \"orders\": [1, 2]}. It's the common format apps use to send and receive information.",
    ],
    related: ["api", "rest"],
  },
  {
    slug: "database",
    term: "Database",
    category: "Data",
    oneLiner: "An organized store of data an app can search, add to, and update fast.",
    analogy: "A very tidy filing cabinet — or a giant, well-structured spreadsheet.",
    detail: [
      "A database keeps your app's data (users, orders, products) safely and lets you query it quickly. Apps talk to it constantly, in the background.",
      "SQL databases store data in linked tables; NoSQL databases use more flexible formats.",
    ],
    related: ["sql-vs-nosql", "backend", "cache"],
    course: { label: "SQLingo", href: "/courses/sql" },
  },
  {
    slug: "sql-vs-nosql",
    term: "SQL vs NoSQL",
    category: "Data",
    oneLiner: "Two families of database: strict tidy tables vs flexible free-form documents.",
    analogy: "SQL is a spreadsheet with fixed columns everyone must fill in; NoSQL is a folder of documents you can shape however you like.",
    detail: [
      "SQL databases keep data in strict tables with fixed columns — great when your data is neat and connected, like customers and their orders. NoSQL databases store looser, free-form documents, trading some of that structure for flexibility and easier growth to very large size.",
      "Most everyday business data fits SQL well; NoSQL shines for huge scale or data whose shape keeps changing.",
    ],
    related: ["database"],
    course: { label: "SQLingo", href: "/courses/sql" },
  },
  {
    slug: "cache",
    term: "Cache",
    category: "Data",
    oneLiner: "A saved copy of an answer so you don't redo expensive work.",
    analogy: "A sticky note of a phone number you look up often, so you don't dig through the whole book each time.",
    detail: [
      "Caching stores the result of a slow operation (a database query, a rendered page) and serves the copy on repeat requests — much faster.",
      "The trick is knowing when to throw the copy away so users don't see stale data.",
    ],
    related: ["cdn", "database", "server"],
  },
  {
    slug: "docker",
    term: "Docker & containers",
    category: "Infrastructure",
    oneLiner: "A way to package an app with everything it needs so it runs the same anywhere.",
    analogy: "A shipping container: a standard box that works on any truck, ship, or crane, no matter what's inside.",
    detail: [
      "Docker packs your app plus its libraries and settings into an image. A running copy of that image is a container.",
      "Because the box carries its own environment, 'it works on my machine' stops being a problem — it works the same on your laptop and in production.",
    ],
    related: ["container-vs-vm", "ci-cd", "environment-variables"],
    course: { label: "Dev: DevOps", href: "/courses/dev-devops" },
  },
  {
    slug: "container-vs-vm",
    term: "Container vs virtual machine",
    category: "Infrastructure",
    figure: `<table class="iq-table"><thead><tr><th></th><th>Virtual machine</th><th>Container</th></tr></thead><tbody><tr><td>Includes</td><td>A full guest OS</td><td>Just the app + deps</td></tr><tr><td>Size</td><td>Gigabytes</td><td>Megabytes</td></tr><tr><td>Starts in</td><td>Minutes</td><td>Seconds</td></tr></tbody></table>`,
    oneLiner: "Both isolate apps, but a container is far lighter than a VM.",
    analogy: "A VM is a whole separate house with its own foundation; a container is a furnished room that shares the building's plumbing and power.",
    detail: [
      "A virtual machine runs a whole second operating system inside your computer — powerful, but heavy and slow to start. A container skips that: it shares the computer's existing operating system and packs only the app plus the extra bits it needs.",
      "So a container gives you most of the same separation for a tiny fraction of the size and startup time.",
    ],
    related: ["docker", "server"],
  },
  {
    slug: "nginx",
    term: "nginx",
    category: "Infrastructure",
    oneLiner: "A fast web server that greets requests and routes them to the right place.",
    analogy: "The receptionist of a building: it asks every visitor where they're going and directs them to the right office — and handles the front-desk chores like security and mail.",
    detail: [
      "nginx is often the first thing a request reaches. It can hand back simple files itself, pass everything else on to your app, and take care of security (HTTPS) and sharing traffic across several servers.",
      "It's commonly used as a reverse proxy sitting in front of app servers like gunicorn.",
    ],
    related: ["reverse-proxy", "load-balancer", "gunicorn", "server"],
    course: { label: "Dev: DevOps", href: "/courses/dev-devops" },
  },
  {
    slug: "reverse-proxy",
    term: "Reverse proxy",
    category: "Infrastructure",
    figure: `<div class="iq-flow"><span>Client</span><i>&rarr;</i><span>Reverse proxy (nginx)</span><i>&rarr;</i><span>App servers</span></div>`,
    oneLiner: "A front desk that receives all requests and passes them to the right server behind it.",
    analogy: "A building receptionist: visitors never wander to the offices directly — they check in at the desk, which sends them to the right place.",
    detail: [
      "A reverse proxy sits in front of one or more servers. Visitors only ever talk to it; it quietly passes each request to the right server behind it and returns the answer.",
      "Putting one in front lets you handle security, caching, and traffic-sharing all in one place, and keeps your actual servers hidden. nginx is a popular one.",
    ],
    related: ["proxy", "nginx", "load-balancer", "server"],
    course: { label: "Dev: Fundamentals", href: "/courses/dev-fundamentals" },
  },
  {
    slug: "proxy",
    term: "Proxy (forward proxy)",
    category: "Infrastructure",
    oneLiner: "A middleman that makes requests on your behalf and hides who you are.",
    analogy: "A personal assistant who makes calls for you — the other side only ever sees the assistant, not you.",
    detail: [
      "A forward proxy sits in front of clients: your request goes to the proxy, which fetches the resource and passes it back. Used for privacy, filtering, or caching.",
      "It's the mirror image of a reverse proxy: a forward proxy hides the client; a reverse proxy hides the servers.",
    ],
    related: ["reverse-proxy", "nginx"],
  },
  {
    slug: "load-balancer",
    term: "Load balancer",
    category: "Infrastructure",
    figure: `<div class="iq-flow"><span>Requests</span><i>&rarr;</i><span>Load balancer</span><i>&rarr;</i><span>Server A · B · C</span></div>`,
    oneLiner: "Spreads incoming traffic across many servers so none gets overwhelmed.",
    analogy: "The host at a busy restaurant, seating guests evenly across all the waiters.",
    detail: [
      "When one server can't handle all the traffic, you run several and put a load balancer in front. It distributes requests and skips any server that's unhealthy.",
      "This is how sites stay fast and available under heavy load.",
    ],
    related: ["reverse-proxy", "nginx", "server"],
  },
  {
    slug: "gunicorn",
    term: "Gunicorn & WSGI",
    category: "Infrastructure",
    oneLiner: "The engine that actually runs your Python web app and hands it requests.",
    analogy: "If nginx is the receptionist out front, gunicorn is the office manager inside who assigns each task to a worker.",
    detail: [
      "A web server like nginx is great at greeting visitors, but it can't actually run your Python code. Gunicorn is what runs it: it keeps several copies of your app ready and hands each incoming request to one that's free.",
      "\"WSGI\" is simply the agreed way these two connect. You rarely touch it directly — you just run your app with gunicorn sitting behind nginx.",
    ],
    related: ["nginx", "reverse-proxy", "server", "backend"],
    course: { label: "Dev: DevOps", href: "/courses/dev-devops" },
  },
  {
    slug: "cdn",
    term: "CDN",
    category: "Infrastructure",
    oneLiner: "Copies of your files stored worldwide so users load them from nearby.",
    analogy: "Local library branches instead of one central library — you borrow from the nearest one.",
    detail: [
      "A Content Delivery Network caches static assets (images, CSS, JS) on servers around the globe. Users get them from the closest location, which cuts loading time and takes load off your origin server.",
    ],
    related: ["cache", "dns", "server"],
  },
  {
    slug: "port",
    term: "Port",
    category: "Infrastructure",
    oneLiner: "A numbered door on a computer so many services can share one address.",
    analogy: "Apartment numbers at a single street address — same building, different doors.",
    detail: [
      "One machine has one IP address but can run many services, each listening on a different port. Web traffic uses port 80 (HTTP) and 443 (HTTPS) by default.",
    ],
    related: ["server", "http-https"],
  },
  {
    slug: "environment-variables",
    term: "Environment variables",
    category: "Dev workflow",
    oneLiner: "Settings passed to an app from outside, instead of hard-coded in it.",
    analogy: "Dials you set on a machine for each venue, without rebuilding the machine itself.",
    detail: [
      "Things like the database URL or an API key change between your laptop, staging, and production. Storing them as environment variables lets the same code run everywhere with different settings.",
      "Secrets (passwords, keys) are kept this way too — never written directly in the code.",
    ],
    related: ["docker", "ci-cd", "backend"],
  },
  {
    slug: "ci-cd",
    term: "CI/CD",
    category: "Dev workflow",
    figure: `<div class="iq-flow"><span>Commit</span><i>&rarr;</i><span>Build</span><i>&rarr;</i><span>Test</span><i>&rarr;</i><span>Deploy</span></div>`,
    oneLiner: "An automated assembly line that builds, tests, and ships your code.",
    analogy: "A conveyor belt with quality-control checks: every change rolls down it and only ships if it passes.",
    detail: [
      "CI (continuous integration) automatically builds and tests every change so problems show up early. CD (continuous delivery/deployment) automatically releases changes that pass.",
      "Together they make small, safe, frequent releases instead of scary big ones.",
    ],
    related: ["docker", "git", "environment-variables"],
    course: { label: "Dev: DevOps", href: "/courses/dev-devops" },
  },
  {
    slug: "framework-vs-library",
    term: "Framework vs library",
    category: "Dev workflow",
    oneLiner: "A library is a tool you call; a framework is the structure that calls you.",
    analogy: "A library is a power drill you pick up when you need it; a framework is the house frame you build your rooms inside.",
    detail: [
      "You call a library whenever you want (e.g. a date-formatting tool). A framework provides the overall skeleton and calls your code at the right moments — 'don't call us, we'll call you.'",
      "Django and FastAPI are frameworks; a small helper package is a library.",
    ],
    related: ["backend", "compiler-vs-interpreter"],
  },
  {
    slug: "compiler-vs-interpreter",
    term: "Compiler vs interpreter",
    category: "Dev workflow",
    oneLiner: "Two ways to turn code into something the computer runs.",
    analogy: "A compiler translates the whole recipe into the computer's language ahead of time; an interpreter reads and cooks line by line as it goes.",
    detail: [
      "Compiled languages (C, Go, Rust) are translated to machine code before running — fast, with errors caught up front. Interpreted languages (Python, JavaScript) run line by line — flexible, with errors often surfacing at run time.",
      "Some languages (Java, C#) do a bit of both.",
    ],
    related: ["framework-vs-library"],
    course: { label: "Dev: Python", href: "/courses/dev-python" },
  },
  {
    slug: "git",
    term: "Git",
    category: "Dev workflow",
    oneLiner: "A save-and-undo system for code that lets teams work together safely.",
    analogy: "Google Docs version history for code — unlimited undo, plus separate 'timelines' (branches) you can merge back.",
    detail: [
      "Git tracks every change so you can review history, undo mistakes, and work on features in parallel branches. It's how teams edit the same codebase without overwriting each other.",
      "Services like GitHub host Git repositories online for collaboration.",
    ],
    related: ["ci-cd"],
    course: { label: "Dev: Fundamentals", href: "/courses/dev-fundamentals" },
  },
  {
    slug: "authentication-vs-authorization",
    term: "Authentication vs authorization",
    category: "Security & auth",
    oneLiner: "Authentication is proving who you are. Authorization is what you're allowed to do.",
    analogy: "At an office: showing your ID badge at the door is authentication. Whether that badge also opens the server room is authorization.",
    detail: [
      "They sound alike and often happen together, but they answer different questions. First the system checks you're really you (log in). Then, for each thing you try to do, it checks you're allowed.",
      "That's why you can be logged in (authenticated) but still get \"you don't have permission\" (not authorized).",
    ],
    related: ["jwt", "oauth", "cookies-vs-sessions"],
  },
  {
    slug: "cookies-vs-sessions",
    term: "Cookies & sessions",
    category: "Security & auth",
    oneLiner: "How a website remembers who you are between clicks.",
    analogy: "A coat-check ticket. When you log in, the site hands your browser a little ticket (a cookie). Each time you return, your browser shows the ticket so the site knows it's still you.",
    detail: [
      "The web forgets you between requests by default, so sites give your browser a small piece of text (a cookie) to hand back each time.",
      "Often the cookie just holds a random ID, and the real details about you sit safely on the server — that server-side memory is called a session.",
    ],
    related: ["jwt", "authentication-vs-authorization"],
  },
  {
    slug: "jwt",
    term: "JWT (token)",
    category: "Security & auth",
    oneLiner: "A tamper-proof pass a site gives you after login, which you show on each request.",
    analogy: "A festival wristband. Once you're checked in, you just flash the wristband instead of showing your ID and ticket again at every stage.",
    detail: [
      "JWT means JSON Web Token. After you log in, the server gives you a signed token; your app sends it with each request to prove who you are.",
      "It's signed so the server can tell if anyone tampered with it. Unlike a session, the server doesn't have to remember it — the token carries the proof.",
    ],
    related: ["cookies-vs-sessions", "authentication-vs-authorization", "oauth"],
  },
  {
    slug: "oauth",
    term: "OAuth",
    category: "Security & auth",
    oneLiner: "Logging into one app using another account, without sharing your password.",
    analogy: "A valet key: it lets the valet park your car but not open the glovebox. \"Log in with Google\" lets an app confirm who you are through Google, without Google handing over your password.",
    figure: `<div class="iq-flow"><span>You</span><i>&rarr;</i><span>App</span><i>&rarr;</i><span>\"Log in with Google\"</span><i>&rarr;</i><span>App gets permission</span></div>`,
    detail: [
      "Instead of making a new password, you let a trusted provider (Google, GitHub, Apple) vouch for you. The app never sees your password — only a limited permission the provider grants.",
      "It's why one leaked app can't expose your Google password.",
    ],
    related: ["jwt", "authentication-vs-authorization", "api-key"],
  },
  {
    slug: "hashing-vs-encryption",
    term: "Hashing vs encryption",
    category: "Security & auth",
    oneLiner: "Two ways to protect data — encryption can be undone with a key; hashing can't.",
    analogy: "Encryption is a locked box you can reopen with the right key. Hashing is a blender — you can't turn the smoothie back into fruit.",
    detail: [
      "Encryption scrambles data so only someone with the key can read it again — used when data must be recovered later (like a private message).",
      "Hashing is one-way: it turns input into a fixed fingerprint that can't be reversed. That's how passwords are stored — the site checks the fingerprint, never the actual password.",
    ],
    related: ["http-https", "jwt"],
  },
  {
    slug: "cors",
    term: "CORS",
    category: "Security & auth",
    oneLiner: "A browser rule about which other websites are allowed to call a given service.",
    analogy: "A guest list at the door. The service says which websites may talk to it; the browser turns everyone else away.",
    detail: [
      "By default, a web page can't freely call an API on a different domain — a safety measure. CORS is how the service says \"these specific sites are allowed.\"",
      "If you've seen a \"blocked by CORS policy\" error, it means the service didn't put your site on its guest list.",
    ],
    related: ["api", "http-https"],
  },
  {
    slug: "api-key",
    term: "API key",
    category: "Security & auth",
    oneLiner: "A secret password that identifies your app when it calls someone else's service.",
    analogy: "A membership card with your name on it — it proves the request is really from you, and can be cancelled if it's lost.",
    detail: [
      "When your app uses another company's API, it usually sends an API key so they know who's calling, can track usage, and can bill or rate-limit you.",
      "Keys are secrets: they're kept out of the code (in environment variables) and revoked if they leak.",
    ],
    related: ["api", "rate-limiting", "environment-variables"],
  },
  {
    slug: "rate-limiting",
    term: "Rate limiting",
    category: "Security & auth",
    oneLiner: "A cap on how many requests you can make in a short time.",
    analogy: "A \"one free sample per customer\" rule — it stops any single person from overwhelming the counter.",
    detail: [
      "Services limit how often you can call them to prevent abuse, accidental floods, and overload. Go over the limit and you get a \"429 Too Many Requests\" response.",
    ],
    related: ["api", "api-key", "load-balancer"],
  },
  {
    slug: "webhook",
    term: "Webhook",
    category: "Web basics",
    oneLiner: "Instead of you constantly asking \"anything new?\", the other service calls you when something happens.",
    analogy: "A doorbell instead of checking the peephole every minute. The visitor rings you when they arrive.",
    figure: `<div class="iq-flow"><span>Their server</span><i>&mdash; something happens &rarr;</i><span>calls your URL</span></div>`,
    detail: [
      "Normally your app asks a service for updates over and over (polling), which is wasteful. A webhook flips it: you give the service a URL, and it sends you a message the moment an event occurs (a payment, a new message).",
      "It's how apps react instantly without constantly refreshing.",
    ],
    related: ["api", "websocket"],
  },
  {
    slug: "websocket",
    term: "WebSocket",
    category: "Web basics",
    oneLiner: "An always-open, two-way connection between browser and server for live updates.",
    analogy: "A phone call, where both sides can talk anytime — versus posting letters back and forth (normal web requests).",
    detail: [
      "Regular web requests are one-and-done: ask, get an answer, hang up. A WebSocket stays open so the server can push new data instantly.",
      "It powers live chat, notifications, multiplayer games, and live dashboards.",
    ],
    related: ["http-https", "webhook", "api"],
  },
  {
    slug: "graphql",
    term: "GraphQL",
    category: "Web basics",
    oneLiner: "A way to ask an API for exactly the data you want — no more, no less.",
    analogy: "A build-your-own-plate buffet instead of a fixed set meal: you take precisely what you need.",
    detail: [
      "With a normal (REST) API you often get fixed chunks of data, sometimes too much or too little. GraphQL lets the app specify the exact fields it wants in one request.",
      "It's an alternative style of API, popular for complex apps.",
    ],
    related: ["api", "rest", "json"],
  },
  {
    slug: "ip-address",
    term: "IP address",
    category: "Web basics",
    oneLiner: "The numeric address of a device on a network.",
    analogy: "A postal address for computers — it's where data gets delivered.",
    detail: [
      "Every device online has an IP address (like 142.250.72.14). It's how data finds the right machine.",
      "Because numbers are hard to remember, DNS lets us type names like google.com instead.",
    ],
    related: ["dns", "port", "localhost"],
  },
  {
    slug: "localhost",
    term: "localhost",
    category: "Web basics",
    oneLiner: "Your own computer, when it's talking to itself.",
    analogy: "A sticky note you leave on your own desk. \"localhost\" just means \"right here, this machine.\"",
    detail: [
      "While building an app you run it on your own computer and open it at localhost (address 127.0.0.1). Only you can see it — it's not on the internet yet.",
      "You'll usually add a port too, like localhost:3000, to reach a specific program.",
    ],
    related: ["ip-address", "port", "server"],
  },
  {
    slug: "orm",
    term: "ORM",
    category: "Data",
    oneLiner: "A translator that lets you work with database data as normal code, instead of writing SQL by hand.",
    analogy: "A bilingual assistant: you speak in your language (code), and it speaks to the database in SQL for you.",
    detail: [
      "ORM stands for Object-Relational Mapper. It maps database rows to objects in your code, so you can write customers.create(...) instead of raw SQL.",
      "It saves time and reduces mistakes, though you sometimes still drop to SQL for tricky queries.",
    ],
    related: ["database", "sql-vs-nosql", "schema"],
    course: { label: "Dev: Django", href: "/courses/dev-django" },
  },
  {
    slug: "database-index",
    term: "Database index",
    category: "Data",
    oneLiner: "An extra lookup structure that makes searching a database fast.",
    analogy: "The index at the back of a book. Instead of reading every page to find a topic, you jump straight to the right one.",
    figure: `<table class="iq-table"><thead><tr><th>Find city = 'Mumbai'</th><th>Rows the database checks</th></tr></thead><tbody><tr><td>Without an index</td><td>All 1,000,000</td></tr><tr><td>With an index</td><td>Just the ~50 that match</td></tr></tbody></table>`,
    detail: [
      "As tables grow, searching every row gets slow. An index keeps a sorted shortcut for chosen columns so the database can jump to matches.",
      "The trade-off: indexes speed up reads but slightly slow down writes and use extra space, so you add them where you search most.",
    ],
    related: ["database", "primary-foreign-key", "schema"],
    course: { label: "SQLingo", href: "/courses/sql" },
  },
  {
    slug: "primary-foreign-key",
    term: "Primary key & foreign key",
    category: "Data",
    oneLiner: "A primary key uniquely names each row; a foreign key points to a row in another table.",
    analogy: "A primary key is your unique ID number. A foreign key on an order is that order noting down which customer's ID it belongs to.",
    detail: [
      "A primary key (like an id column) is guaranteed unique, so each row can be pinpointed. A foreign key stores another table's key to link records together.",
      "This is how a database keeps orders connected to the right customers.",
    ],
    related: ["database", "schema", "database-index"],
    course: { label: "SQLingo", href: "/courses/sql" },
  },
  {
    slug: "schema",
    term: "Schema",
    category: "Data",
    oneLiner: "The blueprint of a database: what tables and columns exist, and their rules.",
    analogy: "The blank form design — which boxes exist and what each one accepts — before anyone fills it in.",
    detail: [
      "A schema defines the structure: table names, columns, data types, and rules (like \"email must be unique\"). It's decided up front in SQL databases.",
      "Changing it later is done through migrations.",
    ],
    related: ["database", "migration", "sql-vs-nosql"],
  },
  {
    slug: "migration",
    term: "Database migration",
    category: "Data",
    oneLiner: "A tracked, repeatable change to a database's structure.",
    analogy: "A dated renovation plan for a building — everyone applies the same changes, in the same order.",
    detail: [
      "When you need a new column or table, you write a migration: a small file describing the change. Running it updates the database, and teammates run the same file to stay in sync.",
      "It keeps every copy of the database (yours, staging, production) matching.",
    ],
    related: ["schema", "database", "ci-cd"],
    course: { label: "Dev: Django", href: "/courses/dev-django" },
  },
  {
    slug: "transaction",
    term: "Transaction",
    category: "Data",
    oneLiner: "A group of database changes that all succeed together, or not at all.",
    analogy: "A bank transfer: money must leave one account AND arrive in the other. It should never do just one half.",
    detail: [
      "Some actions need several steps that must not be left half-done. A transaction wraps them so either every step commits, or if anything fails, they all roll back as if nothing happened.",
    ],
    related: ["database", "sql-vs-nosql"],
    course: { label: "SQLingo", href: "/courses/sql" },
  },
  {
    slug: "message-queue",
    term: "Message queue",
    category: "Data",
    oneLiner: "A waiting line for tasks, so slow work can be done later instead of making the user wait.",
    analogy: "A ticket queue at a busy deli: you drop your order and a worker picks it up when free — you don't stand frozen at the counter.",
    figure: `<div class="iq-flow"><span>App adds a task</span><i>&rarr;</i><span>Queue</span><i>&rarr;</i><span>Worker does it later</span></div>`,
    detail: [
      "If a step is slow (sending email, processing a video), you don't want the user waiting for it. The app drops a message in a queue and responds immediately; a separate worker handles it in the background.",
      "It keeps apps responsive and smooths out spikes in load.",
    ],
    related: ["backend", "synchronous-vs-asynchronous", "scaling"],
  },
  {
    slug: "monolith-vs-microservices",
    term: "Monolith vs microservices",
    category: "Infrastructure",
    oneLiner: "One big app, versus many small connected apps.",
    analogy: "A department store with everything under one roof, versus a street of specialist shops that talk to each other.",
    figure: `<table class="iq-table"><thead><tr><th></th><th>Monolith</th><th>Microservices</th></tr></thead><tbody><tr><td>Shape</td><td>One big app</td><td>Many small apps</td></tr><tr><td>Simple to start</td><td>Yes</td><td>No</td></tr><tr><td>Scale parts alone</td><td>No</td><td>Yes</td></tr></tbody></table>`,
    detail: [
      "A monolith keeps all the code in one deployable app — simple to build and run, harder to scale or change in isolated parts. Microservices split it into small independent services.",
      "Microservices add flexibility but also network and operational complexity. Most projects should start as a monolith and split only when they must.",
    ],
    related: ["backend", "serverless", "scaling"],
  },
  {
    slug: "serverless",
    term: "Serverless",
    category: "Infrastructure",
    oneLiner: "Running your code without managing any servers — the cloud runs it on demand.",
    analogy: "Taking taxis instead of owning a car: you don't maintain anything, you just use it when you need it and pay per ride.",
    detail: [
      "There are still servers, but you don't manage them. You upload a function; the cloud runs it when triggered and scales it automatically, charging only for what runs.",
      "Great for bursty or event-driven work; the trade-offs are cold starts and vendor lock-in.",
    ],
    related: ["scaling", "ci-cd", "backend"],
  },
  {
    slug: "scaling",
    term: "Scaling (horizontal vs vertical)",
    category: "Infrastructure",
    oneLiner: "Handling more users by adding power to one machine, or by adding more machines.",
    analogy: "A busy shop: hire one stronger worker (vertical), or hire more workers (horizontal).",
    figure: `<table class="iq-table"><thead><tr><th></th><th>Vertical</th><th>Horizontal</th></tr></thead><tbody><tr><td>How</td><td>A bigger machine</td><td>More machines</td></tr><tr><td>Ceiling</td><td>Limited by machine size</td><td>Much higher</td></tr><tr><td>Needs</td><td>Simple</td><td>A load balancer</td></tr></tbody></table>`,
    detail: [
      "Vertical scaling upgrades one server — simple, but there's a limit and a single point of failure. Horizontal scaling runs many servers behind a load balancer — scales far further and adds redundancy.",
    ],
    related: ["load-balancer", "stateless-vs-stateful", "serverless"],
  },
  {
    slug: "stateless-vs-stateful",
    term: "Stateless vs stateful",
    category: "Infrastructure",
    oneLiner: "Whether each request stands alone, or the server remembers earlier ones.",
    analogy: "A stateless clerk treats every visit as your first. A stateful one remembers your last conversation.",
    detail: [
      "A stateless service keeps no memory between requests — every request carries what it needs. That makes it easy to run many copies, so stateless design is key to horizontal scaling.",
      "Stateful services remember things (like an in-progress session), which is handy but harder to scale.",
    ],
    related: ["scaling", "cookies-vs-sessions", "load-balancer"],
  },
  {
    slug: "mvc",
    term: "MVC",
    category: "Backend & servers",
    oneLiner: "A common way to organise app code into three parts: data, display, and the logic between them.",
    analogy: "A restaurant: the pantry (Model = data), the plated dish the customer sees (View), and the chef deciding what to make (Controller).",
    figure: `<div class="iq-flow"><span>Model (data)</span><i>&mdash;</i><span>Controller (logic)</span><i>&mdash;</i><span>View (what you see)</span></div>`,
    detail: [
      "MVC (Model-View-Controller) separates the data (Model), the presentation (View), and the logic that connects them (Controller). Django uses a close variant called MVT.",
      "Keeping them separate makes code easier to change without one part breaking another.",
    ],
    related: ["framework-vs-library", "backend", "frontend"],
    course: { label: "Dev: Django", href: "/courses/dev-django" },
  },
  {
    slug: "synchronous-vs-asynchronous",
    term: "Synchronous vs asynchronous",
    category: "Under the hood",
    oneLiner: "Do one thing at a time and wait, versus start something and carry on.",
    analogy: "Synchronous: standing at the microwave until it beeps. Asynchronous: starting it, going to chop vegetables, and coming back when it beeps.",
    figure: `<div class="iq-flow"><span>Sync</span><i>:</i><span>start</span><i>&rarr;</i><span>wait…</span><i>&rarr;</i><span>next</span></div><div class="iq-flow" style="margin-top:8px"><span>Async</span><i>:</i><span>start</span><i>&rarr;</i><span>do other work</span><i>&rarr;</i><span>handle result later</span></div>`,
    detail: [
      "Synchronous code waits for each step to finish before moving on. Asynchronous code kicks off slow work (like a network call) and keeps going, dealing with the result when it arrives.",
      "Async keeps apps responsive instead of freezing while they wait.",
    ],
    related: ["message-queue", "process-vs-thread"],
    course: { label: "Dev: Python", href: "/courses/dev-python" },
  },
  {
    slug: "process-vs-thread",
    term: "Process vs thread",
    category: "Under the hood",
    oneLiner: "A process is a running program with its own memory; threads are workers inside it that share that memory.",
    analogy: "A process is a kitchen. Threads are the cooks in it, sharing the same counters and fridge.",
    detail: [
      "Each program you run is a process with its own private memory. Inside a process, threads let it do several things at once while sharing data.",
      "Sharing memory is fast but needs care, so two threads don't trip over each other.",
    ],
    related: ["synchronous-vs-asynchronous", "ram-vs-storage"],
  },
  {
    slug: "ram-vs-storage",
    term: "RAM vs storage",
    category: "Under the hood",
    oneLiner: "RAM is fast, temporary workspace; storage is slower but keeps data when the power is off.",
    analogy: "RAM is your desk — what you're actively working on. Storage is the filing cabinet — kept long-term.",
    detail: [
      "RAM (memory) holds what a program is using right now; it's very fast but wiped when the machine turns off. Storage (a disk or SSD) is slower but permanent.",
      "That's why unsaved work is lost in a crash: it was only in RAM.",
    ],
    related: ["process-vs-thread", "cache"],
  },
  {
    slug: "exception-handling",
    term: "Exception handling",
    category: "Under the hood",
    oneLiner: "Planning for things that can go wrong so the program doesn't crash.",
    analogy: "A backup plan: \"if the card is declined, ask for another\" — instead of the cashier just freezing.",
    detail: [
      "When something fails (a file is missing, the network drops), the program raises an error, called an exception. Handling it means catching that error and responding sensibly instead of crashing.",
      "Good software expects failure and recovers gracefully.",
    ],
    related: ["testing", "compiler-vs-interpreter"],
    course: { label: "Dev: Python", href: "/courses/dev-python" },
  },
  {
    slug: "package-manager",
    term: "Package manager",
    category: "Dev workflow",
    oneLiner: "A tool that installs and updates the outside code your project depends on.",
    analogy: "An app store for code libraries — it fetches them, keeps them updated, and sorts out what needs what.",
    detail: [
      "Rather than copying other people's code by hand, you list what you need and a package manager downloads it and its own requirements. Python uses pip; JavaScript uses npm.",
    ],
    related: ["dependency", "semantic-versioning", "framework-vs-library"],
  },
  {
    slug: "dependency",
    term: "Dependency",
    category: "Dev workflow",
    oneLiner: "Outside code your project relies on to work.",
    analogy: "Ingredients you buy instead of growing yourself — your recipe depends on them being there.",
    detail: [
      "Most projects use libraries written by others (for dates, payments, and so on). Each is a dependency. They save huge effort, but you have to keep them updated and secure.",
    ],
    related: ["package-manager", "semantic-versioning", "framework-vs-library"],
  },
  {
    slug: "semantic-versioning",
    term: "Semantic versioning",
    category: "Dev workflow",
    oneLiner: "A version-number rule (like 2.4.1) that signals how big a change is.",
    analogy: "Big.medium.small. The first number jumps on a major, possibly-breaking change; the last on a tiny fix.",
    detail: [
      "Versions read as MAJOR.MINOR.PATCH. A new PATCH is a safe bug fix, a new MINOR adds features without breaking anything, and a new MAJOR may break older code.",
      "It tells you at a glance whether an update is risky.",
    ],
    related: ["dependency", "package-manager"],
  },
  {
    slug: "linter-formatter",
    term: "Linter & formatter",
    category: "Dev workflow",
    oneLiner: "Tools that automatically catch sloppy code and tidy its style.",
    analogy: "Spellcheck and auto-format, but for code.",
    detail: [
      "A linter flags likely mistakes and bad patterns; a formatter rewrites your code to a consistent style automatically. Together they keep a codebase clean and readable, especially across a team.",
    ],
    related: ["testing", "git"],
  },
  {
    slug: "testing",
    term: "Automated testing",
    category: "Dev workflow",
    oneLiner: "Getting the computer to check that your code does what it should.",
    analogy: "A checklist a robot runs every time you change something, so breakages are caught immediately.",
    detail: [
      "Instead of manually clicking through everything after each change, you write small tests that verify behaviour and run automatically. Unit tests check one piece; integration tests check pieces working together.",
      "They run in CI so bugs are caught before release.",
    ],
    related: ["ci-cd", "exception-handling", "linter-formatter"],
    course: { label: "QA Track", href: "/courses/qa" },
  },
  {
    slug: "terminal-cli",
    term: "Terminal (command line)",
    category: "Dev workflow",
    oneLiner: "A text-based way to control your computer by typing commands.",
    analogy: "Talking to your computer with typed instructions instead of clicking — slower to learn, much faster once you know the words.",
    detail: [
      "The terminal (or command line) lets you run tools, move files, and manage projects by typing. Most developer tools — Git, package managers, deployment — are driven from here.",
      "It looks intimidating but you only need a handful of commands to start.",
    ],
    related: ["git", "package-manager"],
    course: { label: "Dev: Fundamentals", href: "/courses/dev-fundamentals" },
  },
];

export const bySlug = Object.fromEntries(terms.map((t) => [t.slug, t]));
